// @ts-check
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";
import starlight from "@astrojs/starlight";
import tailwindcss from "@tailwindcss/vite";

// Single static Astro build that owns both the marketing/blog site and the
// Starlight documentation:
//
//   - output: static (no SSR Worker — there is no server/API surface today)
//   - trailingSlash: "ignore" + build.format: "directory" → directory output
//     (foo/index.html) so BOTH /docs/ and /docs resolve on Cloudflare Pages
//     (ignore matches either variant; Pages serves the directory index), and
//     the canonical URL stays /docs/ via Astro.url. "never"/"file" forbade
//     /docs/ entirely (hard 404 in dev AND prod) and broke the sidebar's own
//     /docs/ link; "always" would symmetrically 404 the no-slash internal
//     links the .mdx bodies use — only "ignore" serves both without rewrites.
//   - outDir: dist/client stays the deploy directory
//   - docs served at /docs/** by nesting Starlight content under
//     src/content/docs/docs/** (Starlight-at-a-subpath); do NOT set base:"/docs"
//   - pagefind:false — keep the existing post-build `npx pagefind --site
//     dist/client` step as the single owner of the combined index for now
export default defineConfig({
  site: "https://gpui-query.freeoxide.com",
  trailingSlash: "ignore",
  output: "static",
  outDir: "dist/client",
  build: {
    format: "directory",
  },
  integrations: [
    // Starlight must come BEFORE mdx(): it injects astro-expressive-code, which
    // has to precede the MDX integration so code blocks render correctly.
    starlight({
      title: "gpui-query Docs",
      logo: {
        src: "./src/assets/logo.svg",
      },
      // Starlight defaults to /favicon.svg, which this project doesn't ship —
      // the canonical favicon is /favicon.ico (same one the manifest references).
      // Starlight derives the MIME type
      // from the extension (image/x-icon).
      favicon: "/favicon.ico",
      customCss: ["./src/styles/starlight.css"],
      // Override Starlight's <Head> to strip the trailing `.html` that
      // build.format:"file" leaves on canonical/og:url (see the override file).
      components: {
        Head: "./src/components/overrides/Head.astro",
      },
      // Docs-wide OG fallback image (generated by scripts/generate-og-images.ts
      // into public/og/docs.png). Individual pages can override via frontmatter.
      head: [
        {
          tag: "meta",
          attrs: {
            property: "og:image",
            content: "https://gpui-query.freeoxide.com/og/docs.png",
          },
        },
        {
          tag: "meta",
          attrs: { name: "twitter:card", content: "summary_large_image" },
        },
      ],
      // First cut: keep the existing post-build Pagefind index for the combined
      // marketing/blog/docs output. Re-enable Starlight search only if it is
      // wired to the same final index or replaces the global search.
      pagefind: false,
      social: [
        {
          icon: "github",
          label: "GitHub",
          href: "https://github.com/freeoxide/gpui-query",
        },
      ],
      // Explicit sidebar (not autogenerated) so the section order and route
      // inventory stay stable regardless of file additions.
      sidebar: [
        { label: "Introduction", link: "/docs/" },
        {
          label: "Getting Started",
          items: [
            { label: "Installation", link: "/docs/getting-started/installation" },
            { label: "Quick Start", link: "/docs/getting-started/quick-start" },
          ],
        },
        {
          label: "API Reference",
          items: [
            { label: "Queries", link: "/docs/api/queries" },
            { label: "Mutations", link: "/docs/api/mutations" },
            { label: "Infinite Queries", link: "/docs/api/infinite-queries" },
            { label: "QueryClient", link: "/docs/api/query-client" },
          ],
        },
        {
          label: "Guides",
          items: [
            { label: "Caching", link: "/docs/guides/caching" },
            { label: "Error handling", link: "/docs/guides/error-handling" },
            { label: "Retry", link: "/docs/guides/retry" },
            { label: "Persistence", link: "/docs/guides/persistence" },
            { label: "HTTP cache headers", link: "/docs/guides/http-caching" },
            { label: "Query Keys", link: "/docs/guides/query-keys" },
            { label: "The Select Pattern", link: "/docs/guides/select-pattern" },
            { label: "Claude Code skills", link: "/docs/guides/claude-skills" },
          ],
        },
        {
          label: "Advanced",
          items: [
            { label: "Devtools", link: "/docs/advanced/devtools" },
            { label: "Observers", link: "/docs/advanced/observers" },
            { label: "gpui-query vs. raw async", link: "/docs/advanced/comparison" },
            { label: "API Reference", link: "/docs/advanced/api-reference" },
            { label: "Migrating from v1 to v2", link: "/docs/advanced/migration" },
          ],
        },
      ],
      credits: false,
      disable404Route: true,
    }),
    mdx(),
  ],
  vite: {
    plugins: [tailwindcss()],
    resolve: {
      alias: {
        "#": new URL("./src", import.meta.url).pathname,
        "@": new URL("./src", import.meta.url).pathname,
      },
    },
  },
});
